CREATE SCHEMA IF NOT EXISTS test_1;

drop table if exists test_1.action_one CASCADE;
drop table if exists test_1.action_one_two CASCADE;
drop table if exists test_1.action_two CASCADE;
drop table if exists test_1.area CASCADE;
drop table if exists test_1.car CASCADE;
drop table if exists test_1.property_one CASCADE;
drop table if exists test_1.property_two CASCADE;
drop table if exists test_1.type_object CASCADE;

create table test_1.car
(
    id   bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);

create table test_1.area
(
    id      bigint generated by default as identity,
    code    bigint,
    id_car  bigint,
    id_type bigint,
    primary key (id)
);

create table test_1.action_one
(
    id      bigint generated by default as identity,
    id_area bigint,
    id_type bigint,
    number_action  bigint,
    primary key (id)
);

create table test_1.action_two
(
    id     bigint generated by default as identity,
    number_action bigint,
    primary key (id)
);

create table test_1.property_one
(
    id        bigint generated by default as identity,
    id_action bigint,
    value     bigint,
    primary key (id)
);

create table test_1.property_two
(
    id        bigint generated by default as identity,
    id_action bigint,
    value     bigint,
    primary key (id)
);

create table test_1.action_one_two
(
    id_one bigint not null,
    id_two bigint not null,
    primary key (id_one, id_two)
);

create table test_1.type_object
(
    id   bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);
