CREATE SCHEMA IF NOT EXISTS test_1;

drop table if exists test_1.area CASCADE;
drop table if exists test_1.car CASCADE;

create table test_1.area
(
    id     bigint generated by default as identity,
    code   bigint,
    id_car bigint,
    primary key (id)
);


create table test_1.car
(
    id   bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);






