server:
  port: ${PORT:8080}

spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
#    url: jdbc:h2:mem:memDb;DB_CLOSE_DELAY=-1
    url: jdbc:h2:file:./data/db6
    driverClassName: org.h2.Driver
    username: sa
    password:

  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none


logging:
  level:
    org.springframework.orm.jpa: ERROR
    org.springframework.transaction: ERROR